[{u'categories': [{u'alias': u'parks', u'title': u'Parks'}],
   u'coordinates': {u'latitude': 37.7879384, u'longitude': -122.4075056},
   u'id': u'union-square-plaza-san-francisco',
   u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/OB2NDnPEVscQfT3VWW6Jxg/o.jpg',
   u'location': {u'address1': u'333 Post St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94108'},
   u'name': u'Union Square Plaza',
   u'phone': u'+14158315500',
   u'rating': 4.0,
   u'review_count': 440,
   u'url': u'https://www.yelp.com/biz/union-square-plaza-san-francisco'},
  
  {u'categories': [{u'alias': u'parks', u'title': u'Parks'}],
   u'coordinates': {u'latitude': 37.7848643788333,
                    u'longitude': -122.402581932663},
   u'id': u'yerba-buena-gardens-san-francisco',
   u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/OxPlqMtfR71Z7r_xmBnWqg/o.jpg',
   u'location': {u'address1': u'745 Mission St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94103'},
   u'name': u'Yerba Buena Gardens',
   u'phone': u'+14158203550',
   u'rating': 4.5,
   u'review_count': 351,
   u'url': u'https://www.yelp.com/biz/yerba-buena-gardens-san-francisco'},
  
  {u'categories': [{u'alias': u'parks', u'title': u'Parks'}],
   u'coordinates': {u'latitude': 37.7877464, u'longitude': -122.4039383},
   u'id': u'one-kearny-san-francisco',
   u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/EyFQlNfjt9BzMqO63p-x9w/o.jpg',
   u'location': {u'address1': u'23 Geary St',
                 u'address2': u'Ste 510',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94108'},
   u'name': u'One Kearny',
   u'phone': u'+14157881133',
   u'rating': 4.5,
   u'review_count': 29,
   u'url': u'https://www.yelp.com/biz/one-kearny-san-francisco'},
  
  {u'categories': [{u'alias': u'boating', u'title': u'Boating'},
                   {u'alias': u'boatcharters', u'title': u'Boat Charters'}],
   u'coordinates': {u'latitude': 37.78138, u'longitude': -122.4214},
   u'id': u'captain-kirks-san-francisco-sailing-san-francisco',
   u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/n47k_neGs2uWUu_jlH_csA/o.jpg',
   u'location': {u'address1': u'601 Van Ness Ave',
                 u'address2': u'Ste E-736',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94102'},
   u'name': u"Captain Kirk's San Francisco Sailing",
   u'phone': u'+16509300740',
   u'rating': 5.0,
   u'review_count': 297,
   u'url': u'https://www.yelp.com/biz/captain-kirks-san-francisco-sailing-san-francisco'},
  
  {u'categories': [{u'alias': u'escapegames', u'title': u'Escape Games'}],
   u'coordinates': {u'latitude': 37.7937546372414,
                    u'longitude': -122.404572442174},
   u'id': u'escapesf-san-francisco',
   u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/qJ2jt4WRyI47jo7Z5rAUbw/o.jpg',
   u'location': {u'address1': u'602 Kearny St',
                 u'address2': None,
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94108'},
   u'name': u'EscapeSF',
   u'phone': u'+14152941718',
   u'rating': 4.5,
   u'review_count': 114,
   u'url': u'https://www.yelp.com/biz/escapesf-san-francisco'}],
 
 [{u'categories': [{u'alias': u'bakeries', u'title': u'Bakeries'}],
   u'coordinates': {u'latitude': 37.7875909362522,
                    u'longitude': -122.418352626264},
   u'id': u'mr-holmes-bakehouse-san-francisco',
   u'image_url': u'http://s3-media2.fl.yelpcdn.com/bphoto/r-729P1kW3cjqZ_Mi3Ljvw/o.jpg',
   u'location': {u'address1': u'1042 Larkin St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94109'},
   u'name': u'Mr Holmes Bakehouse',
   u'phone': u'+14158297700',
   u'price': u'$$',
   u'rating': 4.0,
   u'review_count': 1022,
   u'url': u'https://www.yelp.com/biz/mr-holmes-bakehouse-san-francisco'},
  
  {u'categories': [{u'alias': u'bakeries', u'title': u'Bakeries'}],
   u'coordinates': {u'latitude': 37.7905129, u'longitude': -122.4171723},
   u'id': u'flour-and-co-san-francisco-3',
   u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/h9cqz8jWt9pUqCjJ5fz9RA/o.jpg',
   u'location': {u'address1': u'1030 Hyde St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94109'},
   u'name': u'Flour & Co',
   u'phone': u'+14159927620',
   u'price': u'$',
   u'rating': 4.5,
   u'review_count': 377,
   u'url': u'https://www.yelp.com/biz/flour-and-co-san-francisco-3'},
  
  {u'categories': [{u'alias': u'bakeries', u'title': u'Bakeries'},
                   {u'alias': u'desserts', u'title': u'Desserts'}],
   u'coordinates': {u'latitude': 37.7963362634182,
                    u'longitude': -122.406742349267},
   u'id': u'golden-gate-bakery-san-francisco',
   u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/NafhoH7VGwPi6FqmxQIkUQ/o.jpg',
   u'location': {u'address1': u'1029 Grant Ave',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94133'},
   u'name': u'Golden Gate Bakery',
   u'phone': u'+14157812627',
   u'price': u'$',
   u'rating': 4.5,
   u'review_count': 2650,
   u'url': u'https://www.yelp.com/biz/golden-gate-bakery-san-francisco'},
  
  {u'categories': [{u'alias': u'bakeries', u'title': u'Bakeries'}],
   u'coordinates': {u'latitude': 37.78681, u'longitude': -122.407436},
   u'id': u'tout-sweet-p\xe2tisserie-san-francisco-4',
   u'image_url': u'http://s3-media4.fl.yelpcdn.com/bphoto/9ROe2Xl3aXOXhfCHhXh-Wg/o.jpg',
   u'location': {u'address1': u"170 O'Farrell St",
                 u'address2': u'3 Fl',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94102'},
   u'name': u'Tout Sweet P\xe2tisserie',
   u'phone': u'+14153851679',
   u'price': u'$$',
   u'rating': 4.0,
   u'review_count': 383,
   u'url': u'https://www.yelp.com/biz/tout-sweet-p%C3%A2tisserie-san-francisco-4'},
  
  {u'categories': [{u'alias': u'bakeries', u'title': u'Bakeries'},
                   {u'alias': u'donuts', u'title': u'Donuts'}],
   u'coordinates': {u'latitude': 37.7918499, u'longitude': -122.42128},
   u'id': u'bobs-donut-and-pastry-shop-san-francisco-2',
   u'image_url': u'http://s3-media4.fl.yelpcdn.com/bphoto/EQBGfs7fogePbf8TanUJsw/o.jpg',
   u'location': {u'address1': u'1621 Polk St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94109'},
   u'name': u"Bob's Donut & Pastry Shop",
   u'phone': u'+14157763141',
   u'price': u'$',
   u'rating': 4.5,
   u'review_count': 2163,
   u'url': u'https://www.yelp.com/biz/bobs-donut-and-pastry-shop-san-francisco-2'}],
 
 [{u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}],
   u'coordinates': {u'latitude': 37.782352, u'longitude': -122.407697},
   u'id': u'blue-bottle-coffee-co-san-francisco-7',
   u'image_url': u'http://s3-media2.fl.yelpcdn.com/bphoto/YKoMObZPbtVi1l7f3g4xwg/o.jpg',
   u'location': {u'address1': u'66 Mint St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94103'},
   u'name': u'Blue Bottle Coffee Co',
   u'phone': u'+15106533394',
   u'price': u'$$',
   u'rating': 4.0,
   u'review_count': 1857,
   u'url': u'https://www.yelp.com/biz/blue-bottle-coffee-co-san-francisco-7'},
  
  {u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'},
                   {u'alias': u'sandwiches', u'title': u'Sandwiches'},
                   {u'alias': u'bagels', u'title': u'Bagels'}],
   u'coordinates': {u'latitude': 37.7901517599821,
                    u'longitude': -122.409288436174},
   u'id': u'beanstalk-cafe-san-francisco-2',
   u'image_url': u'http://s3-media2.fl.yelpcdn.com/bphoto/yvw6fgMum8gpS4b4WIFrEA/o.jpg',
   u'location': {u'address1': u'724 Bush St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94108'},
   u'name': u'Beanstalk Cafe',
   u'phone': u'+14155761966',
   u'price': u'$',
   u'rating': 4.5,
   u'review_count': 509,
   u'url': u'https://www.yelp.com/biz/beanstalk-cafe-san-francisco-2'},
  
  {u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'},
                   {u'alias': u'sandwiches', u'title': u'Sandwiches'},
                   {u'alias': u'vietnamese', u'title': u'Vietnamese'}],
   u'coordinates': {u'latitude': 37.79001, u'longitude': -122.41177},
   u'id': u'fresh-brew-coffee-san-francisco',
   u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/G0xDrpOQyXxrrKnQrYm7iQ/o.jpg',
   u'location': {u'address1': u'882 Bush St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94108'},
   u'name': u'Fresh Brew Coffee',
   u'phone': u'+14155670915',
   u'price': u'$',
   u'rating': 4.5,
   u'review_count': 347,
   u'url': u'https://www.yelp.com/biz/fresh-brew-coffee-san-francisco'},
  
  {u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}],
   u'coordinates': {u'latitude': 37.791405, u'longitude': -122.419327},
   u'id': u'contraband-coffee-bar-san-francisco',
   u'image_url': u'http://s3-media4.fl.yelpcdn.com/bphoto/42V-yDiNZcfLFT743jxmPA/o.jpg',
   u'location': {u'address1': u'1415 Larkin St',
                 u'address2': u'',
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94109'},
   u'name': u'Contraband Coffee Bar',
   u'phone': u'+14158397388',
   u'price': u'$$',
   u'rating': 4.0,
   u'review_count': 593,
   u'url': u'https://www.yelp.com/biz/contraband-coffee-bar-san-francisco'},
  
  {u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}],
   u'coordinates': {u'latitude': 37.7882923185825,
                    u'longitude': -122.404029965401},
   u'id': u'iron-horse-coffee-bar-san-francisco',
   u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/_eMt3Li_B5DdeAkHFsxIJA/o.jpg',
   u'location': {u'address1': u'25 Maiden Ln',
                 u'address2': None,
                 u'address3': u'',
                 u'city': u'San Francisco',
                 u'country': u'US',
                 u'state': u'CA',
                 u'zip_code': u'94108'},
   u'name': u'Iron Horse Coffee Bar',
   u'price': u'$',
   u'rating': 4.5,
   u'review_count': 60,
   u'url': u'https://www.yelp.com/biz/iron-horse-coffee-bar-san-francisco'}]

storing_yelp_values= {}
    #Returns 5 of the first things in the first activity type FIXME: VARIETY
    
    # loop over the r.json() to build up the yelp_response dictionary
    for yelp_request in activity_types:
            r = requests.get("https://api.yelp.com/v3/businesses/search?location={}cll={},{}&limit=5&sort=1&term={}&category_filter={}".format(end_location, end_lat, end_lng, yelp_request, yelp_request), headers=payload)
            print "\n\n\n\n this the yelp get request \n\n\n", r.json()
            yelp_values = r.json()['businesses'] #getting to the key/values with the good stuff

            for business in yelp_values:  #go through each business in the json response
                #nesting dictionaries
                storing_yelp_values[name] =  {}
                #setting the key in big dict to the name of the business 
                name = business['name']
                
                # setting the values in name key in big dict
                storing_yelp_values[name]['address'] = business['location']
                storing_yelp_values[name]['coordinates'] = {'lat': business['coordinates']['latitude'], 
                                                            'lng': business['coordinates']['longitude']}
                storing_yelp_values[name]['phone'] = business['phone']

hard coded sort = 1
{'activity': {u'total': 4458, u'businesses': 
[{u'rating': 4.0, u'review_count': 1856, u'name': u'Blue Bottle Coffee Co', u'url': u'https://www.yelp.com/biz/blue-bottle-coffee-co-san-francisco-7', u'price': u'$$', 
u'coordinates': {u'latitude': 37.782352, u'longitude': -122.407697}, u'phone': u'+15106533394', u'image_url': u'http://s3-media2.fl.yelpcdn.com/bphoto/YKoMObZPbtVi1l7f3g4xwg/o.jpg', 
u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'66 Mint St', u'zip_code': u'94103'}, u'id': u'blue-bottle-coffee-co-san-francisco-7', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}]}, {u'rating': 4.5, u'review_count': 509, u'name': u'Beanstalk Cafe', u'url': u'https://www.yelp.com/biz/beanstalk-cafe-san-francisco-2', u'price': u'$', u'coordinates': {u'latitude': 37.7901517599821, u'longitude': -122.409288436174}, u'phone': u'+14155761966', u'image_url': u'http://s3-media2.fl.yelpcdn.com/bphoto/yvw6fgMum8gpS4b4WIFrEA/o.jpg', u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'724 Bush St', u'zip_code': u'94108'}, u'id': u'beanstalk-cafe-san-francisco-2', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}, {u'alias': u'sandwiches', u'title': u'Sandwiches'}, {u'alias': u'bagels', u'title': u'Bagels'}]}, {u'rating': 4.5, u'review_count': 347, u'name': u'Fresh Brew Coffee', u'url': u'https://www.yelp.com/biz/fresh-brew-coffee-san-francisco', u'price': u'$', u'coordinates': {u'latitude': 37.79001, u'longitude': -122.41177}, u'phone': u'+14155670915', u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/G0xDrpOQyXxrrKnQrYm7iQ/o.jpg', u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'882 Bush St', u'zip_code': u'94108'}, u'id': u'fresh-brew-coffee-san-francisco', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}, {u'alias': u'sandwiches', u'title': u'Sandwiches'}, {u'alias': u'vietnamese', u'title': u'Vietnamese'}]}, {u'rating': 4.0, u'review_count': 593, u'name': u'Contraband Coffee Bar', u'url': u'https://www.yelp.com/biz/contraband-coffee-bar-san-francisco', u'price': u'$$', u'coordinates': {u'latitude': 37.791405, u'longitude': -122.419327}, u'phone': u'+14158397388', u'image_url': u'http://s3-media4.fl.yelpcdn.com/bphoto/42V-yDiNZcfLFT743jxmPA/o.jpg', u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'1415 Larkin St', u'zip_code': u'94109'}, u'id': u'contraband-coffee-bar-san-francisco', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}]}, 
{u'rating': 4.5, u'review_count': 60, u'name': u'Iron Horse Coffee Bar', u'url': u'https://www.yelp.com/biz/iron-horse-coffee-bar-san-francisco', u'price': u'$', u'coordinates': {u'latitude': 37.7882923185825, u'longitude': -122.404029965401}, u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/_eMt3Li_B5DdeAkHFsxIJA/o.jpg', u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': None, u'address3': u'', u'state': u'CA', u'address1': u'25 Maiden Ln', u'zip_code': u'94108'}, u'id': u'iron-horse-coffee-bar-san-francisco', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}]}]}}

changing term to category_filter
{'activity': 
    {u'total': 24875, u'businesses': 
        [{u'rating': 4.5, u'review_count': 337, 
          u'name': u'Tadu Ethiopian Kitchen', u'url': u'https://www.yelp.com/biz/tadu-ethiopian-kitchen-san-francisco-3', u'price': u'$$', 
          u'coordinates': {u'latitude': 37.7847934, u'longitude': -122.4141884}, u'phone': u'+14154096649', u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/EapkmG5rpJuy7u8tu01GYA/o.jpg', 
          u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'484 Ellis St', u'zip_code': u'94102'}, u'id': u'tadu-ethiopian-kitchen-san-francisco-3', u'categories': [{u'alias': u'ethiopian', u'title': u'Ethiopian'}]}, {u'rating': 4.5, u'review_count': 938, u'name': u'Liholiho Yacht Club', u'url': u'https://www.yelp.com/biz/liholiho-yacht-club-san-francisco-2', u'price': u'$$$', u'coordinates': {u'latitude': 37.7883678084094, u'longitude': -122.414625026286}, u'phone': u'+14154405446', u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/uUkGwA2rrwd24RUjIzWmsw/o.jpg', u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'871 Sutter St', u'zip_code': u'94109'}, u'id': u'liholiho-yacht-club-san-francisco-2', u'categories': [{u'alias': u'asianfusion', u'title': u'Asian Fusion'}, {u'alias': u'newamerican', u'title': u'American (New)'}, {u'alias': u'seafood', u'title': u'Seafood'}]}, {u'rating': 4.5, u'review_count': 347, u'name': u'Fresh Brew Coffee', u'url': u'https://www.yelp.com/biz/fresh-brew-coffee-san-francisco', u'price': u'$', u'coordinates': {u'latitude': 37.79001, u'longitude': -122.41177}, u'phone': u'+14155670915', u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/G0xDrpOQyXxrrKnQrYm7iQ/o.jpg', u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'882 Bush St', u'zip_code': u'94108'}, u'id': u'fresh-brew-coffee-san-francisco', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}, {u'alias': u'sandwiches', u'title': u'Sandwiches'}, {u'alias': u'vietnamese', u'title': u'Vietnamese'}]}, {u'rating': 4.5, u'review_count': 254, u'name': u"Hooker's Sweet Treats", u'url': u'https://www.yelp.com/biz/hookers-sweet-treats-san-francisco', u'price': u'$$', u'coordinates': {u'latitude': 37.7852285, u'longitude': -122.4160527}, u'phone': u'+14154414628', u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/izW5V7ghPnQSf6HCIxvS4Q/o.jpg', u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'442 Hyde St', u'zip_code': u'94109'}, u'id': u'hookers-sweet-treats-san-francisco', u'categories': [{u'alias': u'chocolate', u'title': u'Chocolatiers & Shops'}, {u'alias': u'coffee', u'title': u'Coffee & Tea'}]}, {u'rating': 4.5, u'review_count': 153, u'name': u'Tacorea', u'url': u'https://www.yelp.com/biz/tacorea-san-francisco', u'price': u'$', u'coordinates': {u'latitude': 37.7897959388507, u'longitude': -122.410720065236}, u'phone': u'+14158851325', u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/TNkHvAH9s6ctXYHG-gNViw/o.jpg', 
    u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': None, u'state': u'CA', u'address1': u'809 Bush St', u'zip_code': u'94108'}, u'id': u'tacorea-san-francisco', u'categories': [{u'alias': u'asianfusion', u'title': u'Asian Fusion'}, {u'alias': u'mexican', u'title': u'Mexican'}, {u'alias': u'korean', u'title': u'Korean'}]}]}}

term not category_filter
{'activity': 
    {u'total': 4458, u'businesses': 
            [{u'rating': 4.0, u'review_count': 1855, 
              u'name': u'Blue Bottle Coffee Co', u'url': u'https://www.yelp.com/biz/blue-bottle-coffee-co-san-francisco-7', u'price': u'$$', 
              u'coordinates': {u'latitude': 37.782352, u'longitude': -122.407697}, 
              u'phone': u'+15106533394', u'image_url': u'http://s3-media2.fl.yelpcdn.com/bphoto/YKoMObZPbtVi1l7f3g4xwg/o.jpg', 
              u'location': {u'city': u'San Francisco', u'address1': u'66 Mint St', u'address2': u'', u'address3': u'', u'state': u'CA', u'country': u'US', u'zip_code': u'94103'}, 
              u'id': u'blue-bottle-coffee-co-san-francisco-7', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}]}, 

            {u'rating': 4.5, u'review_count': 509, 
            u'name': u'Beanstalk Cafe', u'url': u'https://www.yelp.com/biz/beanstalk-cafe-san-francisco-2', u'price': u'$', 
            u'coordinates': {u'latitude': 37.7901517599821, u'longitude': -122.409288436174}, 
            u'phone': u'+14155761966', u'image_url': u'http://s3-media2.fl.yelpcdn.com/bphoto/yvw6fgMum8gpS4b4WIFrEA/o.jpg', 
            u'location': {u'city': u'San Francisco', u'address1': u'724 Bush St', u'address2': u'', u'address3': u'', u'state': u'CA', u'country': u'US', u'zip_code': u'94108'}, 
            u'id': u'beanstalk-cafe-san-francisco-2', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}, {u'alias': u'sandwiches', u'title': u'Sandwiches'}, {u'alias': u'bagels', u'title': u'Bagels'}]}, 

           {u'rating': 4.5, u'review_count': 347, u'name': u'Fresh Brew Coffee', u'url': u'https://www.yelp.com/biz/fresh-brew-coffee-san-francisco', u'price': u'$', 
            u'coordinates': {u'latitude': 37.79001, u'longitude': -122.41177}, 
            u'phone': u'+14155670915', u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/G0xDrpOQyXxrrKnQrYm7iQ/o.jpg', 
            u'location': {u'city': u'San Francisco', u'address1': u'882 Bush St', u'address2': u'', u'address3': u'', u'state': u'CA', u'country': u'US', u'zip_code': u'94108'}, 
            u'id': u'fresh-brew-coffee-san-francisco', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}, {u'alias': u'sandwiches', u'title': u'Sandwiches'}, {u'alias': u'vietnamese', u'title': u'Vietnamese'}]}, 

           {u'rating': 4.0, u'review_count': 593, u'name': u'Contraband Coffee Bar', u'url': u'https://www.yelp.com/biz/contraband-coffee-bar-san-francisco', u'price': u'$$', 
            u'coordinates': {u'latitude': 37.791405, u'longitude': -122.419327}, u'phone': u'+14158397388', u'image_url': u'http://s3-media4.fl.yelpcdn.com/bphoto/42V-yDiNZcfLFT743jxmPA/o.jpg', u'location': {u'city': u'San Francisco', u'address1': u'1415 Larkin St', u'address2': u'', u'address3': u'', u'state': u'CA', u'country': u'US', u'zip_code': u'94109'}, u'id': u'contraband-coffee-bar-san-francisco', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}]}, {u'rating': 4.5, u'review_count': 60, u'name': u'Iron Horse Coffee Bar', u'url': u'https://www.yelp.com/biz/iron-horse-coffee-bar-san-francisco', u'price': u'$', u'coordinates': {u'latitude': 37.7882923185825, u'longitude': -122.404029965401}, u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/_eMt3Li_B5DdeAkHFsxIJA/o.jpg', u'location': {u'city': u'San Francisco', u'address1': u'25 Maiden Ln', u'address2': None, u'address3': u'', u'state': u'CA', u'country': u'US', u'zip_code': u'94108'}, u'id': u'iron-horse-coffee-bar-san-francisco', u'categories': [{u'alias': u'coffee', u'title': u'Coffee & Tea'}]}]}}






{u'total': 3747, 
u'businesses': 
    [{u'rating': 4.0, u'review_count': 439, 
    u'name': u'Union Square Plaza', u'url': u'https://www.yelp.com/biz/union-square-plaza-san-francisco', 
    u'coordinates': {u'latitude': 37.7879384, u'longitude': -122.4075056}, 
    u'phone': u'+14158315500', u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/OB2NDnPEVscQfT3VWW6Jxg/o.jpg', 
    u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'333 Post St', u'zip_code': u'94108'}, 
    u'id': u'union-square-plaza-san-francisco', u'categories': 
    [{u'alias': u'parks', u'title': u'Parks'}]}, 

    {u'rating': 4.5, u'review_count': 350, 
    u'name': u'Yerba Buena Gardens', u'url': u'https://www.yelp.com/biz/yerba-buena-gardens-san-francisco', 
    u'coordinates': {u'latitude': 37.7848643788333, u'longitude': -122.402581932663}, 
    u'phone': u'+14158203550', u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/OxPlqMtfR71Z7r_xmBnWqg/o.jpg', 
    u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'', u'address3': u'', u'state': u'CA', u'address1': u'745 Mission St', u'zip_code': u'94103'}, 
    u'id': u'yerba-buena-gardens-san-francisco', u'categories': [{u'alias': u'parks', u'title': u'Parks'}]}, 

    {u'rating': 4.5, u'review_count': 29, u'name': u'One Kearny', u'url': u'https://www.yelp.com/biz/one-kearny-san-francisco', 
    u'coordinates': {u'latitude': 37.7877464, u'longitude': -122.4039383}, 
    u'phone': u'+14157881133', u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/EyFQlNfjt9BzMqO63p-x9w/o.jpg', 
    u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'Ste 510', u'address3': u'', u'state': u'CA', u'address1': u'23 Geary St', u'zip_code': u'94108'}, 
    u'id': u'one-kearny-san-francisco', u'categories': [{u'alias': u'parks', u'title': u'Parks'}]}, 

    {u'rating': 5.0, u'review_count': 296, u'name': u"Captain Kirk's San Francisco Sailing", u'url': u'https://www.yelp.com/biz/captain-kirks-san-francisco-sailing-san-francisco', 
    u'coordinates': {u'latitude': 37.78138, u'longitude': -122.4214}, 
    u'phone': u'+16509300740', u'image_url': u'http://s3-media3.fl.yelpcdn.com/bphoto/n47k_neGs2uWUu_jlH_csA/o.jpg', 
    u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': u'Ste E-736', u'address3': u'', u'state': u'CA', u'address1': u'601 Van Ness Ave', u'zip_code': u'94102'}, 
    u'id': u'captain-kirks-san-francisco-sailing-san-francisco', u'categories': [{u'alias': u'boating', u'title': u'Boating'}, {u'alias': u'boatcharters', u'title': u'Boat Charters'}]}, 

    {u'rating': 4.5, u'review_count': 114, u'name': u'EscapeSF', u'url': u'https://www.yelp.com/biz/escapesf-san-francisco', 
    u'coordinates': {u'latitude': 37.7937546372414, u'longitude': -122.404572442174}, 
    u'phone': u'+14152941718', u'image_url': u'http://s3-media1.fl.yelpcdn.com/bphoto/qJ2jt4WRyI47jo7Z5rAUbw/o.jpg', 
    u'location': {u'city': u'San Francisco', u'country': u'US', u'address2': None, u'address3': u'', u'state': u'CA', u'address1': u'602 Kearny St', u'zip_code': u'94108'}, 
    u'id': u'escapesf-san-francisco', u'categories': [{u'alias': u'escapegames', u'title': u'Escape Games'}]}]}
